-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
-- 

-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_lijuapi_errorhandler`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_lijuapi_errorhandler
-- *
-- * When communicating with the Liju Api and something goes wrong in an automated update, this table stores changes
-- *
-- *******************************************************/
CREATE TABLE `civicrm_lijuapi_errorhandler` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique LijuErrorHandler ID',
     `contact_id` int unsigned    COMMENT 'FK to Contact',
     `email` varchar(256) NOT NULL   COMMENT 'Email that is to be changed',
     `email_id` int unsigned    COMMENT 'FK to CiviCRM-Email',
     `is_consumed` tinyint NOT NULL  DEFAULT 0 COMMENT 'True means the API call is succesfull executed',
     `landesverband` varchar(4) NOT NULL   COMMENT 'Landesverband Abbrevation',
     `group_id` int unsigned    COMMENT 'FK to CiviCRM-GroupID',
     `timestamp` timestamp NOT NULL   COMMENT 'Date the Change was attempted',
     `errorcode` varchar(1024) NOT NULL   COMMENT 'Error Code from LiJu API' 
,
        PRIMARY KEY (`id`)
 
 
 
)  ENGINE=InnoDB  ;

 